### ISSUE TITLE
Matching tags backwards

### ISSUE THREAD

**Issue by YaroSpace** [Valloric/MatchTagAlways#13]
I noticed that only the closing tags are matched.  Is there a way to match the opening tags too?  So, when the cursor is on a closing tag, it would highlight the opened tag that it is closing.

**Comment by marceldev89** [comment]
This doesn't seem to work properly when a HTML tag contains some PHP code. Forward lookup is working properly but backward lookup isn't. Using `<?=` or `<?php echo` doesn't make a difference.

```php
<td class="tright">
	<span class="amount color lead">
		<strong>&euro; <?= number_format($sum, 2, ',', ''); ?></strong>
	</span>
</td>
```

**Comment by sandrodz** [comment]
confirm that it doesn't work backwards when there is php inside. this should be reopened.
