### ISSUE TITLE
Not working with handlebars template

### ISSUE THREAD

**Issue by miguelmota** [Valloric/MatchTagAlways#15]
```vim
:set ft?
filetype=hbs syntax=html
```

```vim
let g:mta_filetypes =
      \ get( g:, 'mta_filetypes', {
      \ 'html' : 1,
      \ 'xhtml' : 1,
      \ 'xml' : 1,
      \ 'jinja' : 1,
      \ 'eruby' : 1,
      \ 'htmldjango' : 1,
      \ 'django' : 1,
      \ 'hbs' : 1,
      \} )
```

index.hbs

```html
<div>
 <span>{{name}}</span>
</div>
```

Changing the extension to html works perfectly fine, but it's not working with hbs extension.

**Comment by mcmahoniel** [comment]
When I run ``:set ft?`` on my .hbs file, I get ``filetype=html.handlebars``.

Adding ``\ 'html.handlebars' : 1,`` to my .vimrc makes tag highlighting work properly.

Hope it works for you! :+1:

**Comment by miguelmota** [comment]
Alright so I had to install the bundle [`mustache/vim-mustache-handlebars`](https://github.com/mustache/vim-mustache-handlebars) and then MatchTag worked, as @mcmahoniel mentioned.
