### ISSUE TITLE
Slowdown inside matchings

### ISSUE THREAD

**Issue by humrochagf** [Valloric/MatchTagAlways#18]
When i'm inside some reachable matching tag (*e.g.*: the ones who the opening and closing tags are on the screen), there's a noticeable slowdown on the cursor speed. Probably because of constant pattern checking while moving inside of those.

Looking superficially, one possible solution would be triggering the matching only when entering or leaving a tag level, but i don't know how complex it can be.

I come back with more ideas after looking better the code.

**Comment by Valloric** [comment]
I haven't personally had any perf issues, and this is the first time I've heard of someone complaining about this. You possibly have another Vim plugin (or something else in your vimrc) that's exacerbating the issue in some way. I'd recommend you try to repro this with just MTA loaded.

**Comment by humrochagf** [comment]
I've checked the other plugins and it seems to slow down when in conjuntion with **Vim-Jinja2-Syntax** or **django.vim** plugins

**Comment by Valloric** [comment]
My guess would be that those two plugins have very slow syntax highlighting; either way, if the problem is only apparent with those plugins installed, it means it's unlikely to be an MTA issue.
