### ISSUE TITLE
Does not work for long html tags with a lot of class names, e.g. with bootstrap's grid.

### ISSUE THREAD

**Issue by appendjeff** [Valloric/MatchTagAlways#25]
Line 1 does not match with line 7
![screen shot 2015-11-13 at 4 26 07 pm](https://cloud.githubusercontent.com/assets/15162276/11158043/6c79144e-8a23-11e5-8f3f-601a634403ba.png)

**Comment by appendjeff** [comment]
See the gist: https://gist.github.com/appendjeff/5143e17417958eefe17e

**Comment by staycreativedesign** [comment]
I figured out why remove / from </br> :) on line 2 after <h1>Introducing

**Comment by staycreativedesign** [comment]
@Valloric you can close this :)
