### ISSUE TITLE
Requires Python -> Error output doesn't display properly and is not documented

### ISSUE THREAD

**Issue by Cypher1** [Valloric/MatchTagAlways#26]
If python is not installed the MatchTagAlways bundle will not load properly and will print an error that messes up VIM start

**Comment by kylelamse** [comment]
I get the same issue and I have python and python3 installed

**Comment by Cypher1** [comment]
@kylelamse Which python do you have (python3 is always python3 but python could be 2.x or 3.x)
Also can you comment here to say is you use virtual env or not (I think part of my issue may have been virtual env related).

**Comment by kylelamse** [comment]
@Cypher1 So there are several packages you need to get this to work properly.  I am using neovim and their installation page tells you how to get python modules to work for whatever operating system you're using: [Here](https://github.com/neovim/neovim/wiki/Installing-Neovim).  Let me know if this works for you.

**Comment by Cypher1** [comment]
Thanks kylelamse, I got it working already but I think the plugin can work out if the appropriate python is installed fairly trivially so I still think this is an issue
