### ISSUE TITLE
cursor jumps sporadically

### ISSUE THREAD

**Issue by sandrodz** [Valloric/MatchTagAlways#31]
while typing inside tags cursor appears to jump sporadically and sometimes lag behind typing. this plugin is causing the issue.

![issue demo](http://i.giphy.com/l0EwXRWiafMZYwNri.gif)

iterm2+neovim.

**Comment by Valloric** [comment]
How do you know this plugin is causing the issue? Nothing in MTA moves the cursor.

Can you repro this with vanilla vim instead of neovim? Make sure you have no other plugins loaded since another plugin could be interacting badly with MTA.

**Comment by sandrodz** [comment]
Its simple, I disable plugin and problem goes away. I enable plugin and its apparent.

here I disabled every other plugin including the colorscheme. only thing enabled is your plugin (iterm2):

![demo](http://i.giphy.com/26gsqUrbPIGOj2DgA.gif)

problem persists in terminal.app:
![demo](http://i.giphy.com/26xBS6uKbTjKNWWuk.gif)

**Comment by sandrodz** [comment]
control case, all plugins disabled including MTA:

![demo](http://i.giphy.com/l0Ex3BtYHYW9Cn6AE.gif)

**Comment by sandrodz** [comment]
I can also confirm that this doesn't happen in `vim 8`

![demo](http://i.giphy.com/26gsxaINuSVLcCfwk.gif)

**Comment by Valloric** [comment]
> I can also confirm that this doesn't happen in vim 8 MTA enabled:

Great! That means it's a Vim bug that's been fixed.
