### ISSUE TITLE
MatchTagAlways Python error freezes screen when files are left open for a few minutes

### ISSUE THREAD

**Issue by dvejmz** [Valloric/MatchTagAlways#32]
I recently updated MatchTagAlways to the latest version in master. After doing this I went on to editing some files in Neovim and left them open for a while. When I came back to any one of those files and tried to move the cursor, the window was frozen and displayed the following error:

```
Error detected while processing function <SNR>78_HighlightEnclosingTagsIfPossible[12].
.<SNR>78_HighlightEnclosingTags[1]..<SNR>78_GetEnclosingTagLocations[6]..provider#python#Call:                                                                              
line   18: Invalid channel "1"
```
At this point, no matter what key I pressed on the keyboard, the window would remain frozen showing this error. As soon as I disabled MatchTagAlways in my `init.vim`, the problem disappeared.

Some info about my environment:

* OS: Fedora 24.1
* Neovim 0.1.7
* MatchTagAlways (master)

My MatchTagAlways config is fairly simple:

```vimL
let g:mta_use_matchparen_group = 0
let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'phtml' : 1,
    \ 'php': 1,
    \}
```

If you need any more info from me, just let me know. Thanks.

**Comment by Valloric** [comment]
That strikes me like a Neovim bug. MTA as a plugin has been stable for years. Also, the "channel" stuff is neovim-specific I believe.

@justinmk

**Comment by dvejmz** [comment]
You're probably right, this looks like a problem with Neovim's Python bindings. I'll follow this up with them, thank you for your help, really!
