### ISSUE TITLE
tags not highlighted when off screen

### ISSUE THREAD

**Issue by dylnmc** [Valloric/MatchTagAlways#38]
If, for example, you are inside a `div` tag and you can see the closing `</div>` but you cannot see the opening `<div>`, then, of course, the tags will not be highlighted. Let's say that now, you press `<c-e>` to bring the opening `<div>` into view; the tags are not highlighted until curpos is updated.

Not big deal. Would it be that hard to just highlight tags no matter what? Or does this have something to do with vim's builtin matching/highlighting?

I'm surprised that this is the only plugin for this, honestly. Still nice stuff and thanks.

**Comment by mqudsi** [comment]
iirc, this is in the readme somewhere. It's a performance enhancement so no more than what's on screen needs to be scanned. I think it may also be because it removes the need to save state.

**Comment by dylnmc** [comment]
ok && thanks @mqudsi
